### ISSUE TITLE
Python client fail to display images

### ISSUE THREAD

**Issue by nbmaltais** [iamaisim/ProjectAirSim#210]
## Bug report 

- Project AirSim Version/#commit: v1.0.1
- autopilot version: N/A
- OS Version: Windows 11

### What's the issue you encountered?
When using python exemples in client\cpp\example_user_apps with any of the provided prebuilt environement, the python client fail to display images.

### Settings
NA

### How can the issue be reproduced?

1. Create a python venv
2. Install client library: pip install projectairsim==1.0.1
3. Launch AirSimNH.exe (https://github.com/iamaisim/ProjectAirSim/releases/download/v1.0.1/Neighborhood-Windows-1.0.1.zip)
4. Launch the hello_drone.py exemple
5. Drone is controled but the camera feed are not displayed (this worked in v0.3.0)

### Include full error message in text form

---------------------------------------------------------------
  File "C:\Program Files\Python314\Lib\threading.py", line 1081, in _bootstrap_inner
    self._context.run(self.run)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Program Files\Python314\Lib\threading.py", line 1023, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nbmal\Documents\Work\DroneSimulation\src\ProjectAirSim\client\python\projectairsim\src\projectairsim\image_utils.py", line 166, in display_loop
    self.display_image(
    ~~~~~~~~~~~~~~~~~~^
        image,
        ^^^^^^
    ...<2 lines>...
        win_info["resize_y"],
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\nbmal\Documents\Work\DroneSimulation\src\ProjectAirSim\client\python\projectairsim\src\projectairsim\image_utils.py", line 214, in display_image
    cv2.imshow(win_name, img_np)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(5.0.0) D:/a/opencv-python/opencv-python/opencv/modules/highgui/src/precomp.hpp:182: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'
---------------------------------------------------------------

**What's better than filing an issue? Filing a pull request :).**

**Comment by jonyMarino** [comment]
@nbmaltais thanks for your report. I forgot to test the python client. Please pip install v1.0.2
